parameters:
    packagist_web.archive: []

services:
    packagist.twig.extension:
        class: Packagist\WebBundle\Twig\PackagistExtension
        arguments: [ '@service_container' ]
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    packagist.cache_listener:
        class: Packagist\WebBundle\EventListener\CacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }

    packagist.package_updater:
        class: Packagist\WebBundle\Package\Updater
        arguments: ['@doctrine', '@packagist.dist_config', '@event_dispatcher']

    packagist.dist_config:
        class: Packagist\WebBundle\Service\DistConfig
        arguments: ['@router', '%packagist_web.archive%']

    packagist.in_memory_dumper:
        class: Packagist\WebBundle\Package\InMemoryDumper
        arguments: ['@doctrine', '@packagist.acl_package_checker', '@router']
        public: true

    fos_user.util.user_manipulator:
        class: Packagist\WebBundle\Util\UserManipulator
        arguments:
            - '@fos_user.user_manager'
            - '@fos_user.util.token_generator'
            - '@event_dispatcher'
            - '@request_stack'

    fos_user.form.package_type:
        class: Packagist\WebBundle\Form\Type\PackageType
        arguments: ['@packagist.package_manager']
        tags:
            - { name: form.type }

    packagist.oauth.registration_form:
        factory: ['@form.factory', create]
        class: Symfony\Component\Form\Form
        arguments:
            - 'packagist_oauth_user_registration'

    packagist.download_manager:
        class: Packagist\WebBundle\Model\DownloadManager
        arguments:
            - '@snc_redis.default_client'

    packagist.provider_manager:
        class: Packagist\WebBundle\Model\ProviderManager
        public: true
        arguments:
            - '@snc_redis.default_client'
            - '@doctrine'

    packagist.favorite_manager:
        class: Packagist\WebBundle\Model\FavoriteManager
        arguments:
            - '@snc_redis.default_client'
            - '@doctrine'

    packagist.package_manager:
        class: Packagist\WebBundle\Model\PackageManager
        arguments:
            - '@doctrine'
            - '@mailer'
            - '@twig'
            - '@logger'
            - { from: '%mailer_from_email%', fromName: '%mailer_from_name%' }
            - '@packagist.provider_manager'
            - '@packagist.in_memory_dumper'
            - '@security.authorization_checker'
            - '@packagist_factory'
            - '@event_dispatcher'
            - '@packagist_cache'

    Packagist\WebBundle\Model\PackageManager:
        alias: packagist.package_manager
        public: true

    packagist.profile.form.type:
        class: Packagist\WebBundle\Form\Type\ProfileFormType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type }

    packagist.permission_collection.form.type:
        class: Packagist\WebBundle\Form\Type\GroupAclPermissionCollectionType
        arguments: ['@doctrine']
        tags:
            - { name: form.type }

    packagist.menu_builder:
        class: Packagist\WebBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory', '@security.token_storage', '@translator', '@security.authorization_checker']

    packagist.menu.user:
        class: Knp\Menu\MenuItem
        factory: ['@packagist.menu_builder', createUserMenu]
        tags:
            - { name: knp_menu.menu, alias: user_menu }

    packagist.menu.profile:
        class: Knp\Menu\MenuItem
        factory: ['@packagist.menu_builder', createProfileMenu]
        tags:
            - { name: knp_menu.menu, alias: profile_menu }

    packagist.menu.admin:
        class: Knp\Menu\MenuItem
        factory: ['@packagist.menu_builder', createAdminMenu]
        tags:
            - { name: knp_menu.menu, alias: admin_menu }

    packagist.queue_worker:
        class: Packagist\WebBundle\Service\QueueWorker
        public: true
        arguments:
            - "@packagist.log_resetter"
            - "@snc_redis.default_client"
            - "@doctrine"
            - "@logger"
            - '@Packagist\WebBundle\Service\JobPersister'
            - ~

    scheduler:
        class: Packagist\WebBundle\Service\Scheduler
        arguments: ["@snc_redis.default_client", "@doctrine"]

    packagist.worker_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        public: false
        arguments:
            - []
        tags:
            - { name: container.service_locator }

    Packagist\WebBundle\Service\UpdaterWorker:
        public: false
        arguments:
            - "@logger"
            - "@doctrine"
            - "@packagist.package_updater"
            - '@Symfony\Component\Lock\Factory'
            - "@scheduler"
            - "@packagist.package_manager"
            - "@packagist.download_manager"
            - "@packagist_factory"
            - '@event_dispatcher'
        tags:
            - { name: queue_worker, topic: package:updates }

    Packagist\WebBundle\Webhook\SenderWorker:
        public: false
        arguments:
            - '@serializer'
            - '@doctrine'
            - '@Packagist\WebBundle\Webhook\HookRequestExecutor'
            - '@Packagist\WebBundle\Service\JobScheduler'
            - '@logger'
        tags:
            - { name: queue_worker, topic: webhook:send }

    Packagist\WebBundle\Cron\CronWorker:
        public: false
        arguments:
            - '@okvpn_cron.runner_default'
        tags:
            - { name: queue_worker, topic: cron:execute }

    packagist.cron.worker_middleware:
        class: Packagist\WebBundle\Cron\WorkerMiddleware
        arguments:
            - '@Packagist\WebBundle\Service\JobScheduler'
        tags:
            - { name: okvpn_cron.middleware }

    packagist.log_resetter:
        class: Packagist\WebBundle\Service\LogResetter
        arguments: ['@service_container', '%fingers_crossed_handlers%']

    packagist.console_stack_trace_line_formatter:
        class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
        arguments: []

    packagist_factory:
        class: Packagist\WebBundle\Composer\PackagistFactory
        public: true
        arguments:
            - '@Packagist\WebBundle\Composer\VcsRepositoryFactory'
            - ~
            - '%github_no_api%'

    Packagist\WebBundle\Service\DistManager:
        public: true
        arguments:
            - '@packagist.dist_config'
            - '@packagist_factory'

    Packagist\WebBundle\Composer\PackagistFactory:
        alias: packagist_factory
        public: true

    Packagist\WebBundle\Util\ChangelogUtils:
        public: true
        arguments:
            - '@packagist_factory'

    Packagist\WebBundle\Composer\VcsDriverFactory:
        public: true

    Packagist\WebBundle\Composer\VcsRepositoryFactory:
        public: true
        arguments:
            - '@Packagist\WebBundle\Composer\VcsDriverFactory'

    packagist_cache:
        parent: doctrine_cache.abstract.file_system
        arguments:
            - '%kernel.cache_dir%/packagist'

    Packagist\WebBundle\Validator\Constraint\PackageUniqueValidator:
        arguments:
            - '@doctrine'
            - '@router'
        tags:
            - { name: validator.constraint_validator }

    Packagist\WebBundle\Form\Type\WebhookType:
        arguments:
            - '@security.token_storage'
            - '@packagist.payload_rendered'
        tags:
            - { name: form.type }

    Packagist\WebBundle\Command\CreateUserCommand:
        arguments:
            - '@fos_user.util.user_manipulator'
            - '@fos_user.user_manager'
        tags:
            - { name: console.command }

    # Form extensions
    Packagist\WebBundle\Form\Extension\TooltipExtension:
        tags:
            - { name: form.type_extension, extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }

    Packagist\WebBundle\Webhook\RequestResolver:
        arguments:
            - '@packagist.payload_rendered'
            - '%kernel.project_dir%'

    Packagist\WebBundle\Webhook\HookRequestExecutor:
        arguments:
            - '@Packagist\WebBundle\Webhook\RequestResolver'

    Packagist\WebBundle\Webhook\HookTestAction:
        public: true
        arguments:
            - '@doctrine'
            - '@Packagist\WebBundle\Webhook\HookRequestExecutor'
            - '@security.token_storage'
            - '@request_stack'

    Symfony\Component\Lock\Factory:
        public: true
        alias: lock.default.factory

    Packagist\WebBundle\Service\JobPersister:
        arguments:
            - '@doctrine'

    Packagist\WebBundle\Service\JobScheduler:
        arguments:
            - '@snc_redis.default_client'
            - '@Packagist\WebBundle\Service\JobPersister'

    Packagist\WebBundle\Webhook\Serializer\JobDataSerializer:
        arguments:
            - '@doctrine'
        tags:
            - { name: serializer.normalizer }

    Packagist\WebBundle\Webhook\HookBus:
        arguments:
            - '@serializer'
            - '@Packagist\WebBundle\Service\JobScheduler'

    Packagist\WebBundle\Webhook\EventListener\HookListener:
        arguments:
            - '@doctrine'
            - '@Packagist\WebBundle\Webhook\HookBus'
        tags:
            - { name: kernel.event_listener, event: packageRefresh }
            - { name: kernel.event_listener, event: packagePersist }
            - { name: kernel.event_listener, event: packageError }
            - { name: kernel.event_listener, event: packageRemove }
            - { name: kernel.event_listener, event: security.interactive_login, method: onUserLogin }

    Packagist\WebBundle\Cron\Handler\ScheduleHookHandler:
        arguments:
            - '@Packagist\WebBundle\Webhook\HookBus'
        tags: [okvpn.cron_service]

    Packagist\WebBundle\Cron\WebhookCronLoader:
        arguments: ['@doctrine']
        tags: [okvpn_cron.loader]

    Packagist\WebBundle\Cron\Handler\CleanupDistDir:
        arguments:
            - '@packagist.dist_config'
            - '@logger'
        tags:
            - { name: okvpn.cron, cron: '40 1 */2 * *' }

    Packagist\WebBundle\Cron\Handler\CleanupJobStorage:
        arguments:
            - '@doctrine'
            - '@logger'
        tags:
            - { name: okvpn.cron, cron: '49 0 * * *' }
