<?php

namespace Packeton\Repository;

use Doctrine\Common\Collections\Criteria;
use Packeton\Entity\Webhook;

/**
 * WebhookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebhookRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string|null $package
     * @param array $events
     * @param Criteria|null $criteria
     *
     * @return Webhook[]
     */
    public function findActive(string $package = null, array $events = [], Criteria $criteria = null): array
    {
        $qb = $this->createQueryBuilder('w')
            ->andWhere('w.active = true');
        if (null !== $criteria) {
            $qb->addCriteria($criteria);
        }

        if (count($events) === 1) {
            $qb->andWhere('w.events LIKE :event')
                ->setParameter('event', "%{$events[0]}%");
        }

        $webhooks = $qb->getQuery()->getResult();
        if (null !== $package) {
            $webhooks = array_filter($webhooks, function (Webhook $webhook) use ($package) {
                return $webhook->getPackageRestriction() === null || preg_match($webhook->getPackageRestriction(), $package);
            });
        }

        if ($events) {
            $webhooks = array_filter($webhooks, function (Webhook $webhook) use ($events) {
                return $webhook->matchAnyEvents(...$events);
            });
        }

        return $webhooks;
    }
}
