<?php

namespace Packagist\WebBundle\Repository;

/**
 * WebhookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebhookRepository extends \Doctrine\ORM\EntityRepository
{
}
